version: 2.1
jobs:
  build:
    docker:
      - image: returntocorp/sgrep-build:2.1
    steps:
      - checkout
      - run: apt-get install pkg-config
      - run: cd ~/opam-repository; git pull
      - run: opam update
      - run: opam install yaml
      - run: cd ~
      - run: git clone  https://github.com/returntocorp/pfff
      - run: eval $(opam env) && cd pfff && git checkout bb3d11515b435bf37bdd1863c2839ef8efde9d82 && ./configure && make depend && make && make opt && make install-libs
      - run: cd ~/project
      - run: eval $(opam env); dune build
      - persist_to_workspace:
          root: /home/opam/project
          paths:
            - _build
  test:
    docker:
      - image: returntocorp/sgrep-build:2.1
    steps:
      - checkout
      - attach_workspace:
          at: /home/opam/project
      - run: eval $(opam env); dune runtest
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
